version: '2'
services:
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: app/

  web:
    build: web/
    links:
      - db
    volumes_from:
      - app
    environment:
      VIRTUAL_HOST: claroline.loc
  db:
    image: mysql
    volumes:
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline
