version: '2'
services:
  web:
    build: .
    ports:
      - "99:80"
    links:
      - db
  db:
    image: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline
