version: '2'
services:
  lb:
    restart: always
    image: 'dockercloud/haproxy:latest'
    networks:
      - front
    links:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/apache2/ssl/cert1.pem:/certs/cert1.pem
    environment:
      CERT_FOLDER: /certs/

  web:
    restart: always
    build: web/
    networks:
      - front
      - back
    volumes:
      - data:/var/www/html/claroline
      - /var/www/html/claroline:/var/www/html/claroline:rw
      - /etc/apache2/ssl/cert1.pem:/certs/cert1.pem
    environment:
      VIRTUAL_HOST: http://claroline.loc, https://claroline.loc
  ldap:
      restart: always
      build: ldap/
      networks:
          - back
          - front
      environment:
          LDAP_DOMAIN: example.com
          LDAP_ORGANISATION: example
          LDAP_ADMIN_PASSWORD: admin
          LDAP_TLS: False
    #   volumes:
    #       - ldap:/etc/ldap/slapd.d
  db:
    restart: always
    image: mysql
    networks:
      - back
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline

  chat:
    restart: always
    image: prosody/prosody
    ports:
      - '81:80'
      - '5222:5222'

  tools:
    build: tools/
    volumes:
      - data:/var/www/html/claroline

networks:
  front:
  back:

volumes:
  data:
  mysql:
  ldap:
